### PR TITLE
Replace custom release scripts with a script using xyz

### PR DESCRIPTION
**Pull request by Avaq**
[XYZ](https://github.com/davidchambers/xyz) by David Chambers has some nice utility, like automatically tagging, atomic push, and other safety checks.

New commands for creating releases would be: 

* `npm run release major`
* `npm run release minor`
* `npm run release patch`

### CODE REVIEW

**Review by stoeffel — APPROVED** [review]
👍

**Comment by Avaq** [comment]
Would you mind doing a quick `npm run release minor` (in a clean working directory), to get `futurizeV` out the door? :)
I don't think I would have permission to publish to NPM.

**Comment by stoeffel** [comment]
@Avaq You should have access to npm. Could you try if that's true?

**Comment by stoeffel** [comment]
I published it! so no need for you to try, but you should be able to next time.

**Comment by Avaq** [comment]
Alright, thanks! :+1: :D

**Pull request merged**
